version: "3"

networks:
  discordbotnet_dev:
    external: false
services:
  node:
    image: "node:17"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./Reactbot:/home/node/app
    restart: always
    networks: 
      - discordbotnet_dev
    command: bash -c "npm install && node deploy-commands.js && npm start"